apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: default
data:
  aws_access_key_id: QUtJQTZEQ1pUTU9LRFo3VFdYUDQ=
  aws_secret_access_key: N053ZU14VWF6aUZsaVBNQnc3ZEswMGNmMkZHUnprdGdkeXk4UEdhTA==
